name: RSpec

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
        gemfile:
          - gemfiles/rails_7.2.gemfile
          - gemfiles/rails_7.1.gemfile
          - gemfiles/rails_7.0.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_6.0.gemfile
          - gemfiles/rails_5.2.gemfile
        exclude:
          - gemfile: gemfiles/rails_7.2.gemfile
            ruby: "3.0"
          - gemfile: gemfiles/rails_7.2.gemfile
            ruby: "2.7"
          - gemfile: gemfiles/rails_7.2.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails_7.1.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails_7.0.gemfile
            ruby: "2.6"
          - gemfile: gemfiles/rails_6.1.gemfile
            ruby: "3.3"
          - gemfile: gemfiles/rails_6.1.gemfile
            ruby: "3.2"
          - gemfile: gemfiles/rails_6.1.gemfile
            ruby: "3.1"
          - gemfile: gemfiles/rails_6.0.gemfile
            ruby: "3.3"
          - gemfile: gemfiles/rails_6.0.gemfile
            ruby: "3.2"
          - gemfile: gemfiles/rails_6.0.gemfile
            ruby: "3.1"
          - gemfile: gemfiles/rails_6.0.gemfile
            ruby: "3.0"
          - gemfile: gemfiles/rails_5.2.gemfile
            ruby: "3.3"
          - gemfile: gemfiles/rails_5.2.gemfile
            ruby: "3.2"
          - gemfile: gemfiles/rails_5.2.gemfile
            ruby: "3.1"
          - gemfile: gemfiles/rails_5.2.gemfile
            ruby: "3.0"

    env:
      BUNDLE_GEMFILE: ${{ format('{0}/{1}', github.workspace, matrix.gemfile) }}
      BUNDLE_PATH: ${{ format('{0}/vendor/bundle', github.workspace) }}
      BUNDLE_DEPLOYMENT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec
